USE [master]
GO
/****** Object:  Database [UMISOFT]    Script Date: 12/8/2022 4:45:34 PM ******/
CREATE DATABASE [UMISOFT]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'UMISOFT', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\UMISOFT.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'UMISOFT_log', FILENAME = N'C:\Program Files\Microsoft SQL Server\MSSQL16.MSSQLSERVER\MSSQL\DATA\UMISOFT_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT, LEDGER = OFF
GO
ALTER DATABASE [UMISOFT] SET COMPATIBILITY_LEVEL = 160
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [UMISOFT].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [UMISOFT] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [UMISOFT] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [UMISOFT] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [UMISOFT] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [UMISOFT] SET ARITHABORT OFF 
GO
ALTER DATABASE [UMISOFT] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [UMISOFT] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [UMISOFT] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [UMISOFT] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [UMISOFT] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [UMISOFT] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [UMISOFT] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [UMISOFT] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [UMISOFT] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [UMISOFT] SET  ENABLE_BROKER 
GO
ALTER DATABASE [UMISOFT] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [UMISOFT] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [UMISOFT] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [UMISOFT] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [UMISOFT] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [UMISOFT] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [UMISOFT] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [UMISOFT] SET RECOVERY FULL 
GO
ALTER DATABASE [UMISOFT] SET  MULTI_USER 
GO
ALTER DATABASE [UMISOFT] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [UMISOFT] SET DB_CHAINING OFF 
GO
ALTER DATABASE [UMISOFT] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [UMISOFT] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [UMISOFT] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [UMISOFT] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
EXEC sys.sp_db_vardecimal_storage_format N'UMISOFT', N'ON'
GO
ALTER DATABASE [UMISOFT] SET QUERY_STORE = ON
GO
ALTER DATABASE [UMISOFT] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 30), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 1000, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO
USE [UMISOFT]
GO
/****** Object:  Table [dbo].[DICHVU]    Script Date: 12/8/2022 4:45:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DICHVU](
	[id] [nchar](10) NOT NULL,
	[noiDung] [nvarchar](50) NOT NULL,
	[chiPhi] [money] NOT NULL,
	[thoiGianDuTinhHoanThanh] [int] NULL,
 CONSTRAINT [PK_DICHVU] PRIMARY KEY CLUSTERED 
(
	[id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[DULIEUMAYBAOHANH]    Script Date: 12/8/2022 4:45:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[DULIEUMAYBAOHANH](
	[maMBH] [int] IDENTITY(1,1) NOT NULL,
	[tenMay] [nvarchar](250) NULL,
	[SDT] [varchar](250) NULL,
	[thoiGianBatDauBH] [date] NULL,
	[thoiGianKetThucBH] [date] NULL,
	[idNV] [int] NULL,
PRIMARY KEY CLUSTERED 
(
	[maMBH] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[LOAINHANVIEN]    Script Date: 12/8/2022 4:45:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[LOAINHANVIEN](
	[idLoaiNV] [int] IDENTITY(1,1) NOT NULL,
	[name] [nvarchar](50) NULL,
 CONSTRAINT [PK__LOAINHAN__5BB350D23014157C] PRIMARY KEY CLUSTERED 
(
	[idLoaiNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[NHANVIEN]    Script Date: 12/8/2022 4:45:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[NHANVIEN](
	[idNV] [int] IDENTITY(1,1) NOT NULL,
	[account] [varchar](50) NOT NULL,
	[password] [varchar](50) NOT NULL,
	[name] [nvarchar](50) NULL,
	[idLoaiNV] [int] NULL,
	[tinhTrang] [bit] NULL,
PRIMARY KEY CLUSTERED 
(
	[idNV] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[PHIEUNHAN]    Script Date: 12/8/2022 4:45:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[PHIEUNHAN](
	[maPN] [int] IDENTITY(1,1) NOT NULL,
	[maNVTN] [int] NULL,
	[maNVKT] [int] NULL,
	[nguoiNhan] [nvarchar](50) NULL,
	[noiDung] [nvarchar](250) NULL,
	[moTa] [nvarchar](250) NULL,
	[series] [varchar](250) NULL,
	[trangThai] [nvarchar](50) NULL,
	[chiPhi] [int] NULL,
	[ngayTraMay] [date] NULL,
	[thoiGianTraMay] [date] NULL,
	[SDT] [varchar](50) NULL,
	[ngayTaoPhieu] [date] NULL,
PRIMARY KEY CLUSTERED 
(
	[maPN] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[SOTAIKHOANDANGKI]    Script Date: 12/8/2022 4:45:34 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[SOTAIKHOANDANGKI](
	[sotaikhoan] [int] NULL
) ON [PRIMARY]
GO
ALTER TABLE [dbo].[DULIEUMAYBAOHANH]  WITH CHECK ADD  CONSTRAINT [DULIEUMAY_BH] FOREIGN KEY([idNV])
REFERENCES [dbo].[NHANVIEN] ([idNV])
GO
ALTER TABLE [dbo].[DULIEUMAYBAOHANH] CHECK CONSTRAINT [DULIEUMAY_BH]
GO
ALTER TABLE [dbo].[PHIEUNHAN]  WITH CHECK ADD  CONSTRAINT [PHIEUNHAN_NV] FOREIGN KEY([maNVTN])
REFERENCES [dbo].[NHANVIEN] ([idNV])
GO
ALTER TABLE [dbo].[PHIEUNHAN] CHECK CONSTRAINT [PHIEUNHAN_NV]
GO
USE [master]
GO
ALTER DATABASE [UMISOFT] SET  READ_WRITE 
GO
